environment:
  matrix:
    - node_version: '6'
    - node_version: '8'
    
install:
  - ps: 'Install-Product node $env:node_version'
  - ps: 'npm install --global --production windows-build-tools'
  - npm install

test_script:
  - npm test

build: off
